project:
  type: website
  render:
    - "*.qmd"
    - "!*.ipynb"
    - "!*.md"

website:
  description: "A blog built with Quarto"
  open-graph: true
  site-url: https://your-website-url.example.com # you must change this appropriately for RSS feeds to work properly
  title: "Laboratoire Test Quarto"
  page-footer: |
    <div class="footer-logo-container">
      <img src="/assets/crns.png" loading="lazy" alt="logo CRNS" class="footer-logo" />
      <img src="/assets/cy.png" loading="lazy" alt="logo CRNS" class="footer-logo" />
      <img src="/assets/ensea.png" loading="lazy" alt="logo CRNS" class="footer-logo" />
    </div>
  navbar:
    search: true
    right:
      - text: Blog
        href: posts.qmd
      - text: A propos
        href: about.qmd
      - icon: github
        href: https://github.com/
      - icon: bluesky
        href: https://bsky.app/
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    include-in-header:
      - text: |
          <script src="/assets/nav.js"></script>

lang: fr

