project:
  type: website
  render:
    - "*.qmd"
    - "!*.ipynb"
    - "!*.md"

website:
  description: "A blog built with Quarto"
  site-url: https://your-website-url.example.com # you must change this appropriately for RSS feeds to work properly
  title: "lab-test-etis"
  navbar:
    right:
      - posts.qmd
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: bluesky
        href: https://bsky.app/
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    include-in-header:
      - text: |
          <script src="/assets/nav.js"></script>




