name: Quarto deployment
run-name: ${{ github.actor }} updating the blog
on:
  workflow_dispatch:

jobs:
  deploy_assets:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: SSH credentials
        run: echo "${{secrets.SSH_KEY}}" > ~/deploy_key && chmod 400 ~/deploy_key
      - name: Move files
        run: rsync -Pavz -e "ssh -i ~/deploy_key -o StrictHostKeyChecking=no" ${{ github.workspace }}/_site/  ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/www/test-quarto
